"""add agent pairing, job assignment, and scan credentials

Revision ID: cc60986f55f2
Revises: 9d82756857be
Create Date: 2026-09-11 19:22:08.952958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc60986f55f2'
down_revision: Union[str, Sequence[str], None] = '9d82756857be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    # batch mode: SQLite can't ALTER TABLE ADD CONSTRAINT directly (it rebuilds
    # the table under the hood instead) — Postgres uses the plain ALTER path.
    with op.batch_alter_table('scan_engine') as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_scan_engine_agent_id_agent', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_engine') as batch_op:
        batch_op.drop_constraint('fk_scan_engine_agent_id_agent', type_='foreignkey')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('agent_id')
    op.drop_column('agent', 'api_key_hash')
    op.drop_table('credential')
    # ### end Alembic commands ###
